spring:
  jms:
    listener:
      auto-startup: false
server:
  ssl:
    key-alias: springboot
    key-store: classpath:springboot.jks
    key-store-type: JKS
    key-password: password
    key-store-password: password
    enabled: true
  port: 8080
config:
  queues: # these can be removed if you want to turn off a particular issue
    - SYSTEM.ADMIN.ACCOUNTING.QUEUE # corresponds to application issues
    - SYSTEM.ADMIN.PERFM.EVENT # corresponds to queue service high issues
    - SYSTEM.ADMIN.QMGR.EVENT # corresponds to error rate spikes
    - SYSTEM.ADMIN.STATISTICS.QUEUE # corresponds to activity rate spikes
ibm:
  mq:
    queueManager: QM1
    channel: DEV.ADMIN.SVRCONN
    connName: 13.87.80.195(1414)
    user: admin
    password: passw0rd
