spring:
  jms:
    listener:
      auto-startup: false
server:
  ssl:
    key-alias: springboot
    key-store: classpath:springboot.jks
    key-store-type: JKS
    key-password: password
    key-store-password: password
    enabled: true
  port: 8080