spring:
  jms:
    listener:
      auto-startup: false # DON'T TOUCH

config:
  app:
    connections:
      max: 100 # threshold for how many connections per minute per app
    connectionOperationsRatio:
      connections: 5 # an app must connect more than this quantity per window for the application to consider its connection - operation ratio
      max: 0.8 # ratio of MQCONNs to operations (puts, gets,...) performed by the user in configured time
  queue-manager:
    connections:
      max: 500
    operations:
      max: 700 # maximum num of operations (puts, gets,...) on the queue manager in the configured time
    errors:
      max: 10 # threshold for how many errors per minute is too many, and will cause an issue
  queue:
    errors:
      max: 10 # threshold for how many errors per minute is too many, and will cause an issue
    operationsDefault: 300 # maximum which can be applied to an individual queue
    operationsSpecificQueues:
      DEV.QUEUE.1: 150
      DEV.QUEUE.2: 250
      DEV.QUEUE.3: 180