spring:
  jms:
    listener:
      auto-startup: false

config:
  errors:
    threshold: 10 # threshold for how many errors per minute is too many, and will cause an issue
  apps:
    connections:
      threshold: 100 # threshold for how many connections per minute per app
    connectionOperations:
      connections: 5 # an app must connect more than this quantity per window for the application to consider its connection - operation ratio
      threshold: 0.8 # ratio of MQCONNs to operations (puts, gets,...) performed by the user in configured time
  queueManager:
    connections:
      max: 500
    operations:
      max: 700 # maximum num of operations (puts, gets,...) on the queue manager in the configured time
  queue:
    operations:
      max: 200 # default maximum num of operations (puts, gets,...) on queue in the configured time
      specificQueues: # maximum which can be applied to an individual queue
        DEV.QUEUE.1: 150
        DEV.QUEUE.2: 250
        DEV.QUEUE.3: 180