spring:
  jms:
    listener:
      auto-startup: false
server:
  ssl:
    key-alias: springboot
    key-store: classpath:springboot.jks
    key-store-type: JKS
    key-password: password
    key-store-password: password
    enabled: true
  port: 8080
config:
  app:
    connections:
     max: 10
    connectionOperationsRatio:
      max: 0.8
      connections: 2
  queue-manager:
    connections:
      max: 100
    operations:
      max: 50
    errors:
      max: 5
  queue:
    errors:
      max: 3
    operationsDefault: 300
    operationsSpecificQueues:
      sampleQueue1: 20
      sampleQueue2: 30
