ibmmq:
  container_name: QM4
  image: ibmcom/mq
  ports:
    - "1417:1414"
    - "9446:9443"
  environment:
    - LICENSE=accept
    - MQ_QMGR_NAME=QM4
  volumes:
    - /home/mquser/setup.mqsc:/etc/mqm/20-config.mqsc
  restart: always
