services:
  mqseries:
    image: ibmcom/mq:latest
    ports:
      - "1414:1414"
      - "9443:9443"
    hostname: mq
    environment:
      - LICENSE=accept
      - MQ_QMGR_NAME=QM1
    container_name: mqserver
    stdin_open: true
    tty: true
    restart: always